version: '3.9'

services:
  db:
    container_name: postgresql
    image: postgres:15.3-alpine3.18
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 3s
      retries: 40

  backend:
    container_name: backend
    image: 192.168.10.5:8082/dagestanback:latest
    env_file: .env
    command: sh -c "
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static:/dagestan/static/
      - media:/media/
    depends_on:
      - db
    ports:
      - "8080:8000"

volumes:
  pgdata:
  media:
  static:
